### PR TITLE
feat: switching Web client to the Genx CLI build FUI-1382

### PR DESCRIPTION
**Pull request by cistov**
[Review Guidance](https://www.notion.so/genesisglobal/Platform-Code-Review-Process-ace93ba760cc4563b0dfb712e2a88d8a)

📓 &nbsp; **Related JIRA**

FUI-1382

🤔 &nbsp; **What does this PR do?**

- Switches client/web to the new build system
- Lerna is removed, but folder structure (client/web) has been preserved for now to keep Gradle tasks backards-compatible. client/web will be moved to client once appdev workflows are ready

🚀 &nbsp; **Where should the reviewer start?**

Add file / directory pointers.

📑 &nbsp; **How should this be tested?**

```
npx -y @genesislcap/genx@latest init myapp --ref ac-FUI-1382 -x
```

Then follow the normal approach you'd use to develop a seed app (Intellij plugin/Docker/WSL).

To test the Web client:

```
cd client
npm run bootstrap
API_HOST=wss://public-foundation.genesislab.global/gwf/ npm run dev:intellij
```

✅ &nbsp; **Checklist**

- [x] I have tested my changes.
- [ ] I have added tests for my changes.
- [ ] I have updated the project documentation to reflect my changes.

### CODE REVIEW

**Review by MrBrunoWolff — COMMENTED** [review]
When running this "as it is" (not an app generated from this seed) got this when running `bootstrap`:

image

image

`"ENABLE_SSO": "{{enableSSO}}"` (missing quotes) does the trick

**Comment by MrBrunoWolff** [comment]
When running this "as it is" (not an app generated from this seed) got this when running `dev` script:

image

I need to confirm with the fix from the previous message, but I believe the same may happen with an app generated from this.

**Comment by cistov** [comment]
@MrBrunoWolff running UI directly (without generating an app) isn't expected to work now. Server part of the app never worked without generation and we should be testing that UI and server of the app work together.

> Same happens when creating an app from this seed. "ENABLE_SSO": "{{enableSSO}}" (missing quotes) does the trick

Have you generated the app? You should have `"ENABLE_SSO": true` (or `false`). It's a boolean, so doesn't need the quotes.

**Comment by MrBrunoWolff** [comment]
got it @cistov will focus on "generated app" only, will give it a try now

**Review by MrBrunoWolff — APPROVED** [review]

**Review by SzymonZur — APPROVED** [review]

**Pull request merged**
