### PR TITLE
fix: add lint/stylelint/prettier config packages FUI-1735

### PR DESCRIPTION
**Pull request by SzymonZur**
[Review Guidance](https://www.notion.so/genesisglobal/Platform-Code-Review-Process-ace93ba760cc4563b0dfb712e2a88d8a)

📓 &nbsp; **Related JIRA**

[FUI-1735](https://genesisglobal.atlassian.net/jira/software/c/projects/FUI/issues/FUI-1735)

🤔 &nbsp; **What does this PR do?**

- Add lint/stylelint/prettier config packages to blank-app-seed

🚀 &nbsp; **Where should the reviewer start?**

client/package.json

📑 &nbsp; **How should this be tested?**

```
npx -y @genesislcap/genx@latest init prtest -x --ref sz/FUI-1735
```

✅ &nbsp; **Checklist**

- [x] I have tested my changes.
- [ ] I have added tests for my changes.
- [ ] I have updated the project documentation to reflect my changes.

### CODE REVIEW

**Review by MrBrunoWolff — APPROVED** [review]
Nice!! Happy with the changes

Maybe a follow-up but the actual generated app from the seed is throwing the following:

image

Not a blocker for me but I think we can tweak it so that file works fine

**Comment by SzymonZur** [comment]
@MrBrunoWolff I know, this was left on purpose after the conversation with Artur, as this file needs more investigation

**Comment by cistov** [comment]
> @MrBrunoWolff I know, this was left on purpose after the conversation with Artur, as this file needs more investigation

I had a look, we can fix this one as follows:

```
  "eslintConfig": {
    "extends": "@genesislcap/eslint-config",
    "ignorePatterns": ["**/dist/**", "**/public/**"]
  },
```

Also, we can add the linting step in CI, so we don't accidentally introduce linting errors in future PRs. After the build sample app, we can add the linting step:

```
      - name: Build sample app
        working-directory: /tmp/testapp
        run: ./gradlew build -PclientSpecific=true

      - name: Lint UI code
        working-directory: /tmp/testapp/client
        run: npm run lint
```

**Comment by cistov** [comment]
Looking good:

```
npm run lint
npm info using npm@10.1.0
npm info using node@v20.8.1

> prtest@1.0.0 lint
> genx lint --profile

ℹ Running ESLint...                                                                                                                                            14:59:21
Rule                              | Time (ms) | Relative
:---------------------------------|----------:|--------:
import/namespace                  |  1414.218 |    70.0%
prettier/prettier                 |   521.961 |    25.8%
import/no-extraneous-dependencies |    16.852 |     0.8%
unused-imports/no-unused-imports  |    12.029 |     0.6%
import/order                      |     8.655 |     0.4%
camelcase                         |     7.566 |     0.4%
no-unmodified-loop-condition      |     6.678 |     0.3%
max-len                           |     3.644 |     0.2%
spaced-comment                    |     3.318 |     0.2%
require-atomic-updates            |     2.608 |     0.1%
✔ ESLint completed                                                                                                                                             14:59:28
ℹ Running Stylelint...                                                                                                                                         14:59:28
✔ Stylelint completed
```

**Review by cistov — APPROVED** [review]

**Comment by MrBrunoWolff** [comment]
great stuff/addition @SzymonZur @cistov

**Pull request merged**
